import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, "../data");
const siteDir = join(__dirname, "../site");

// Load benchmarks if available
const benchmarksPath = join(dataDir, "benchmarks.json");
const benchmarks: Record<string, { codingIndex?: number; intelligenceIndex: number; normalizedScore: number }> =
  existsSync(benchmarksPath) ? JSON.parse(readFileSync(benchmarksPath, "utf8")) : {};

function bestCodingIndex(modelIds: string[]): number | null {
  let best: number | null = null;
  for (const id of modelIds) {
    const b = benchmarks[id];
    if (!b) continue;
    const score = b.codingIndex ?? b.intelligenceIndex ?? null;
    if (score != null && (best == null || score > best)) best = score;
  }
  return best;
}

// Load all provider JSON files (skip benchmarks.json)
const providers: Record<string, unknown> = {};
for (const file of readdirSync(dataDir).filter(f => f.endsWith(".json") && f !== "benchmarks.json")) {
  const name = file.replace(".json", "");
  const data = JSON.parse(readFileSync(join(dataDir, file), "utf8")) as {
    plans: Array<{
      model_ids?: string[];
      interactions_monthly: number | null;
      price_usd_monthly: number | null;
      coding_value?: number | null;
      best_coding_index?: number | null;
    }>;
  };

  // Annotate each plan with quality-adjusted value score
  for (const plan of data.plans) {
    const ci = bestCodingIndex(plan.model_ids ?? []);
    plan.best_coding_index = ci;
    if (ci != null && plan.interactions_monthly != null && plan.price_usd_monthly != null && plan.price_usd_monthly > 0) {
      // coding_value: (coding_index × interactions/mo) / price — higher is better value
      plan.coding_value = Math.round((ci * plan.interactions_monthly) / plan.price_usd_monthly);
    } else {
      plan.coding_value = null;
    }
  }

  providers[name] = data;
}

const js = `// Auto-generated by scripts/build-site.ts — do not edit manually
window.CODEPLANS_DATA = ${JSON.stringify(providers, null, 2)};
`;

writeFileSync(join(siteDir, "data.js"), js);
console.log(`Built site/data.js with ${Object.keys(providers).length} providers`);
if (Object.keys(benchmarks).length > 0) {
  console.log(`  Applied benchmark scores from ${Object.keys(benchmarks).length} models`);
}
