import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, "../data");
const siteDir = join(__dirname, "../site");

const providers: Record<string, unknown> = {};

for (const file of readdirSync(dataDir).filter((f) => f.endsWith(".json"))) {
  const name = file.replace(".json", "");
  providers[name] = JSON.parse(readFileSync(join(dataDir, file), "utf8"));
}

const js = `// Auto-generated by scripts/build-site.ts — do not edit manually
window.CODEPLANS_DATA = ${JSON.stringify(providers, null, 2)};
`;

writeFileSync(join(siteDir, "data.js"), js);
console.log(`Built site/data.js with ${Object.keys(providers).length} providers`);
